---
title: Følner sequence
term-aliases:
  - alias: Følner
    id: def-Folner
    translate: false
  - alias: right-Følner
    id: def-rightFolner
  - alias: left-Følner
    id: def-leftFolner
  - alias: tempered
    id: def-tempered
  - alias: Shulman condition
    id: def-tempered
macros:
  - command: Folner
    macro: '{\\Phi}_{#1}'
    variables: 1
    variablesDefault: '{\\vphantom{}}'
dependencies:
  - group
---

# Følner Sequences

::: {#def-rightFolner}
We define a *right-Følner sequence* in $\Group$ as a sequence $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ of finite subsets of $\Group$ satisfying
$$\lim_{N\rightarrow\infty}\frac{\CountingMeasure{\GroupOperation{(\GroupOperation{\Folner[N]}{\Inverse{\GroupElement}})}{\Folner[N]}}}{\CountingMeasure{\Folner[N]}}=1,$$
for all $\GroupElement\in\Group$.
:::

::: {#def-leftFolner}
Similarly, we define a *left-Følner sequence* in $\Group$ as a sequence $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ of finite subsets of $\Group$ satisfying
$$\lim_{N\rightarrow\infty}\frac{\CountingMeasure{(\Inverse{\GroupElement}\cdot\Folner[N])\cap\Folner[N]}}{\CountingMeasure{\Folner[N]}}=1,$$
for all $\GroupElement\in\Group$.
:::

::: {#def-Folner}
We call a sequence in $\Group$ a *Følner sequence* if it is both a left and right Følner sequence.
:::

## Alternative definitions for Monoids

::: {#def-rightFolnerMonoid}

Let $\Monoid$ be a countably-infinite left-cancellative monoid with discrete topology. We define a *left-Følner sequence* in $\Monoid$ as a sequence of finite subsets $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ satisfying
$$\lim_{N\rightarrow\infty}\frac{\CountingMeasure{\MonoidOperation{(\MonoidOperation{\MonoidElement}{\Folner[N]})}{\Folner[N]}}}{\CountingMeasure{\Folner[N]}}=1$$
for all $g\in M$.
:::

::: {#def-leftFolnerMonoid}

Similarly, for a countably-infinite right-cancellative monoid with discrete topology $\Monoid$, we define a *right-Følner sequence* in $\Monoid$ as a sequence of finite subsets $\Folner =(\Folner[N])_{N\in\mathbb{N}}$ satisfying
$$\lim_{N\rightarrow\infty}\frac{\CountingMeasure{\MonoidOperation{(\MonoidOperation{\Folner[N]}{\MonoidElement})}{\Folner[N]}}}{\CountingMeasure{\Folner[N]}}=1$$
for all $g\in M$.
:::

## Equivalent definitions using Set Differences

Equivalent definitions can be constructed by using set differences instead of intersections.

For example, the equivalent definition of a left-Følner sequence, $\Folner$, in $\Monoid$ requires
$$\lim_{N\rightarrow\infty}\frac{\CountingMeasure{(\MonoidOperation{\Folner[N]}{\MonoidElement})\triangle\Folner[N]}}{\CountingMeasure{\Folner[N]}}=0, $$
to be satisfied for all $\MonoidElement\in\Monoid$.

This alternative definition will be useful when looking at proving some of the properties of density.

# Tempered Følner Sequences

::: {#def-tempered}
## @Lindenstrauss2001PETAmenable [Definition 1.1]

A sequence of sets $\Folner=(\Folner[N])_{N\in\mathbb{N}}$ will be said to be *tempered* if, for some $b>0$ and all $n\in\mathbb{N}$,

$$
\CountingMeasure{\bigcup_{1\leq k<N}\Folner[k]^{-1}\Folner[N]}\leq b\CountingMeasure{\Folner[N]}.
$$ {#eq-ShulmanCondition}

is referred to as the *Shulman condition*.
:::

::: {#prp-temperedFolner}
## @Lindenstrauss2001PETAmenable [Proposition 1.4]

1. Every Følner sequence $\Folner=(\Folner[N])_{N\in\mathbb{N}}$ has a tempered subsequence.
2. Every amenable group has a tempered Følner sequence.

:::