---
title: Actions
terms:
  - term: action
    regex: "[Aa]ction"
    id: def-action
    associatedMacros:
    - command: GroupAction
      macro: '{#1}.{#2}'
      variables: 2
    - command: GroupActionPreImage
      macro: '{#1}^{-1}.{#2}'
      variables: 2
  - term: generic
    regex: "[Gg]eneric]"
    id: def-generic
    associatedMacros:
    - command: Generic
      macro: '\\text{gen}({#1},{#2})'
      variables: 2
      variablesDefault:
        - '\\Measure'
        - '\\Folner'
  - term: topological dynamical system
    id: def-topologicalDynamicalSystem
macros:
  - command: KoopmanOperator
    macro: '{U}_{{#1}}{#2}'
    variables: 2
    variablesDefault:
      - '\\GroupElement'
      - '\\vphantom{}'
---

::: {#def-action}
## [[@Bekka2000GroupActionDynamics, Chapter II, Section 2]]{.no-paren}

An *action* of a group, $\Group$, on a measurable space $(X,\SigmaAlgebra{B})$ is a measurable mapping
$$\Group\times X\rightarrow X,\ (\GroupElement,x)\mapsto \GroupAction{\GroupElement}{x} $$
with the following properties:

1. Associativity: For all $\GroupElement,\GroupElement'\in \Group,x\in X$, then $\GroupAction{\GroupElement}{(\GroupAction{\GroupElement'}{x})}=\GroupAction{(\GroupOperation{\GroupElement}{\GroupElement'})}{x}$
2. Identity: There exists an identity element $\GroupIdentity\in\Group$ such that $\GroupAction{\GroupIdentity}{x}=x$ for all $x\in X$.
3. Quasi-Invariance: For any $B\in\SigmaAlgebra{B}$ and for all $\GroupElement\in\Group$, we have $\Measure(\GroupAction{\GroupElement}{B})=0$ if and only if $\Measure(B)=0$.

The action of $\Group$ is also ergodic if it satisfies the additional property:

4. If $B\in\SigmaAlgebra{B}$ and $\Measure(B)=\Measure(\GroupAction{\GroupElement}{B})$ for any $\GroupElement\in\Group$, then $\Measure(B)=0$ or $\Measure(X\setminus B)=0$.

:::

::: {#rem-MonoidAction}
We don't require invertability in order to use actions and could instead use a monoid, $\Monoid$, defining the pre-image of $\Monoid$ on $(X,\SigmaAlgebra{B})$ as a measurable mapping
$$\Monoid\times X\rightarrow \SigmaAlgebra{B},\ (\MonoidElement,x)\mapsto \GroupActionPreImage{\MonoidElement}{x} $$
such that
$$\GroupActionPreImage{\MonoidElement}{x}=\{x'\in X: \GroupAction{\MonoidElement}{x'}=x \}. $$
:::

::: {#def-topologicalDynamicalSystem}

A *topological dynamical system under the action of $\Group$*, denoted $(X,\Group)$, is a compact metric space $X$ that has continuous surjective maps, $(\GroupElement,x)\mapsto \GroupAction{\GroupElement}{x}$, for all $\GroupElement\in\Group$.

:::

::: {#def-generic}

Let $x\in X$, $\Folner=(\Folner[N])_{N\in\mathbb{N}}$ be a Følner sequence in $\Gamma$ and $\Measure$ a probability measure on $X$. Where $\delta_x$ is the Dirac mass at $x$, if
$$\frac{1}{|\Folner[N]|}\sum_{\GroupElement\in\Folner[N]}\delta_{\GroupAction{\GroupElement}{x}}\underset{\text{weakly*}}{\longrightarrow} \Measure \text{ as }N\rightarrow\infty, $$
then we say *$x$ is generic for $\Measure$ with respect to $\Folner$* and we denote this with $x\in\text{gen}(\Measure,\Folner)$.^[consider tempered separately as the FCP construction only depends on sequential compactness]

:::

We are interested in how the action of a group $\Group$ transforms functions on $(X,\SigmaAlgebra{B},\Measure)$ so we must identify the associated definitions within functional analysis.

We define the map $\KoopmanOperator[\GroupElement][]:\text{L}^2(X)\rightarrow\text{L}^2(X)$ where $f\mapsto f\circ \KoopmanOperator[\GroupElement][]$ as the *Koopman operator* induced by $\GroupElement\in\Group$. We find that the Koopman operator induced by $\Group$ is a unitary operator and the group homomorphism $U:\Group\rightarrow\mathscr{U}(\text{L}^2(X))$ is the *unitary representation* of $\Group$ on $\text{L}^2(X)$, where $\mathscr{U}(\text{L}^2(X))$ is the set of all unitary operators on $\text{L}^2(X)$.