---
title: Factor Maps
terms:
  - term: Measurable Factor
    id: def-MeasurableFactor
  - term: Conditional Expectation
    id: def-ConditionalExpectation
  - term: Ergodic Decomposition
    id: def-ErgodicDecomposition
macros:
  - command: ProjectionMap
    macro: '{\\pi}_{#1}'
    variables: 1
    variablesDefault: '\\vphantom{}'
  - command: Expectation
    macro: '{\\mathbb{E}}_{#1}'
    variables: 1
    variablesDefault: '\\Measure'
---

::: {#def-MeasurableFactor}
## [[@kra2022infinite, Definition 2.1]]{.no-paren}

For a system $(X,\Measure,T)$ we say that the system $(Y,\nu,S)$ is a *measurable factor* of $(X,\Measure,T)$ if there is a measurable map $\ProjectionMap:X\rightarrow Y$, the *measurable factor map*, such that $\ProjectionMap(\Measure)=\nu$ and $(S\circ\ProjectionMap)(x)=(\ProjectionMap\circ T)(x)$ for $\Measure$-almost every $x\in X$.
:::

::: {#def-ConditionalExpectation}
## [[@ISem28, Lemma 8.11]]{.no-paren}

Let $(X\SigmaAlgebra{B}),(Y,\SigmaAlgebra{C})$ be probability spaces and let $U:\text{L}^2(X)\rightarrow\text{L}^2(Y)$ be a Markov embedding. The *conditional expectation* of $f\in\text{L}^2(X)$ on $(Y)$ is the orthogonal projection of $f$ on $U(\text{L}^2(Y))$, denoted $\Expectation(f\mid Y)$, such that

1. (Linearity) $f\mapsto\Expectation(f\mid Y)$ is a linear operator from $\text{L}^2(X)$ to $\text{L}^2(Y)$, i.e.,
  $$\Expectation(f+g\mid\SigmaAlgebra{C})=\Expectation(f\mid\SigmaAlgebra{C})+\Expectation(g\mid\SigmaAlgebra{C}).$$
2. (Non-Negative) If $f\geq0$, then $\Expectation(f\mid Y)\geq0$.
3. If $f\in \text{L}^2(Y)$, then $\Expectation(U(f)\mid Y)=f$. In particular, $\Expectation(\mathbb{1}\mid Y)=\mathbb{1}$.
4. If $f\in\text{L}^2(X)$ and $g\in\text{L}^\infty(Y)$, then $\Expectation(fU(g)\mid Y)=g\Expectation(f\mid Y)$.
5. For $f\in\text{L}^2(X)$,
  $$\int_X f\ \mathrm{d}\Measure_X=\int_Y\Expectation(f\mid Y)\ \mathrm{d}\Measure_Y. $$
6. For $f\in\text{L}^2(X)$, the condtional expectation $\Expectation(f\mid Y)$ is the unique element of $\text{L}^2(Y)$ satisfying
  $$\int_Y\Expectation(f\mid Y)h\ \mathrm{d}\Measure_Y=\int_Xf(U(h))\ \mathrm{d}\Measure_X, $$for all $h\in\text{L}^\infty(Y)$.
7. For $f\in\text{L}^2(X)$,
  $$|\Expectation(f\mid Y)|^2\leq\Expectation(|f|^2\mid Y). $$
8. The conditional expectation operator extends to a linear operator from $\text{L}^1(X)$ to $\text{L}^1(Y)$ satisfying the properties (1)-(5). Moreover, it maps each $\text{L}^p(X)$ to $\text{L}^p(Y)$, for $1\leq p\leq\infty$, with $||\Expectation(f\mid Y)||)_{\text{L}^p(Y)}\leq||f||_{\text{L}^p(X)}$ for every $f\in\text{L}^p(X)$.
9. (Monotone Convergence) If $0\leq f_1\leq f_2\leq...$ is a monotone sequence and $f$ is an element in $\text{L}^2(X)$ such that $(f_n)_{n\in\mathbb{N}}$ converges to $f$ almost everywhere, then $\Expectation(f_n\mid Y)$ converges to $\Expectation(f\mid Y)$ almost everywhere.
10. (Dominated Convergence) If $(f_n)_{n\in\mathbb{N}}$ is a sequence and $f$ is an element in $\text{L}^2(X)$ such that $f_n$ converges to $f$ almost everywhere and there is $g\in\text{L}^1(X)$ with $|f_n|\leq g$ almost everywhere for all $n$, then $\Expectation(f_n\mid Y)$ converges to $\Expectation(f\mid Y)$ almost surely.

In the case that $Y=X$, then we instead denote the conditional expectation as $\Expectation(f\mid\SigmaAlgebra{C})$.
:::

Whilst looking at conditional expectations and understanding property (5), we remarked that $\Expectation(f\mid\SigmaAlgebra{C})$ averages a function $f:X\rightarrow\SigmaAlgebra{C}$ in $(X,\SigmaAlgebra{B})$ on each subset in $\SigmaAlgebra{C}$.

::: {#def-Disintegration}
## [[@kra2022infinite, Section 2]]{.no-paren}

Fix a system $(X,\Measure,\Group)$ and a probability space $(\Omega,\nu)$. Whenever we have a map $\omega\mapsto\Measure_\omega$ from $\Omega$ to $\mathcal{M}(X)$, the set of probability measures on $X$, with the properties

1. $\omega\mapsto\Measure_\omega(B)$ is measurable for every Borel set $B\subset X$,
2. $\int_Xf\ \mathrm{d}\Measure=\int_\Omega\int_Xf\ \mathrm{d}\Measure_\omega\ \mathrm{d}\nu(\omega)$ for all measurable and bounded $f:X\rightarrow\mathbb{C}$,

we call $\omega\mapsto\Measure_\omega$ a *disintegration* of $\Measure$.
:::

::: {#thm-FactorMapDisintegration}

If $\pi:(X,\SigmaAlgebra{B},\Measure)\rightarrow(Y,\SigmaAlgebra{C},\nu)$ is a measurable factor map, then there exists a disintegration $y\mapsto\Measure_y$ of $\Measure$ defined on $(Y,\nu)$ such that
$$\Expectation(f\mid Y)(y)=\int_Xf\ d\Measure_y $$
for $\nu$-almost every $y\in Y$, whenever $f:X\rightarrow\mathbb{C}$ is measurable and bounded. Furthermore, if $y\mapsto\eta_y$ is another such disintegration, then $\eta_y=\Measure_y$ for $\nu$-almost every $y\in Y$.
:::

::: {#def-ErgodicDecomposition}
## [[@kra2022infinite, Definition 2.7]]{.no-paren}

Let $(X,\Measure,\Group)$ be a system and $\SigmaAlgebra{C}$ be a $\sigma$-algebra of $G$-invariant Borel sets. An \textit{ergodic decomposition} of $\Measure$ is a disintegration $x\mapsto\Measure_x$ of $\Measure$ defined on $(X,\Measure)$ such that
$$\int_Xf\ d\Measure_x=E(f\mid\SigmaAlgebra{C})(x) $$
holds for $\Measure$-almost every $x\in X$, whenever $f:X\rightarrow\mathbb{C}$ is measurable and bounded.
:::

Notice that, by @thm-FactorMapDisintegration, we immediately have the property that, if $x\mapsto\nu_x$ is another ergodic decomposition of $(X,\Measure,\Group)$, $\Measure_x=\nu_x$ for $\Measure$-almost every $x\in X$.

In working on Exercise 8.5 provided by @ISem28, we also reach the following result:

::: {#thm-ErgodicDecomposition}
## [[cf. @ISem28, Exercise 8.5]]{.no-paren}

For a system $(X,\Measure,\Group)$, there exists an ergodic decomposition $x\mapsto\Measure_x$ where, for $\Measure$-almost every $x\in X$, the measure $\Measure_x$ is $\Group$-invariant and ergodic.
:::

This is proved by starting with @def-Disintegration and @thm-FactorMapDisintegration and using the assumptions that $Y=X$, $\nu=\Measure$, and $\SigmaAlgebra{C}$ is the $\sigma$-algebra of $\Group$-invariant Borel sets. We then use the fact that $\text{L}^2(Y,\SigmaAlgebra{C})\subseteq\text{L}^2(X,\SigmaAlgebra{B})$ to conclude that there exists a Markov embedding
$$U:\text{L}^2(Y,\Sigma_Y,\Measure_Y)\rightarrow\text{L}^2(X,\text{Bor}(X),\Measure_X)$$
where $U(\text{L}^2(Y,\Sigma_Y,\nu))=\text{L}^2(X,\Sigma_Y,\Measure)$. We then show that $(X,\SigmaAlgebra{B},\Measure_y,\Group)$ is a measure-preserving system by showing that $(U_\gamma)_*\Measure_y=\Measure_y$ for every $\gamma\in\Group$ and almost every $y\in Y$ using @thm-FactorMapDisintegration. We conclude the proof by proving ergodicity by arriving to the conclusion that $\Measure_y(E)=\mathbb{1}_E(y)\in\{0,1\}$ for some $E\in\SigmaAlgebra{C}$.