---
title: Measure Theory and Ergodic Theory
terms:
  - alias: topological measure space
    id: def-TopoMeasureSpace
macros:
  - command: Topology
    macro: '{\\tau}'
  - command: SigmaAlgebra
    macro: '{\\mathscr{#1}}'
    variables: 1
  - command: SigmaAlgebraGenerator
    macro: '{\\sigma({#1})}'
    variables: 1
    variablesDefault: '\\Topology'
  - command: Measure
    macro: '{\\mu}'
  - command: LebesgueMeasure
    macro: '{\\left|#1\\right|}'
    variables: 1
    variablesDefault: '\\,\\cdot\\,'
  - command: CountingMeasure
    macro: '{\\lambda}'
dependencies:
  - group
---

The foundational knowledge relating to Measure & Ergodic Theory, that has not been covered elsewhere, was provided by @Robertson2023MeasureErgodicTheory.

::: {#def-TopoMeasureSpace}
## @Gleason2010HaarMeasure [Section 2]

A *topological measure space* $(X,\SigmaAlgebra{B},\Measure)$ is a topological space $(X,\Topology)$ such that $\SigmaAlgebra{B}$ is generated by the open sets defined by the topology $\Topology$, i.e., $\SigmaAlgebra{B}=\text{Borel}(X)=\SigmaAlgebraGenerator$, and $\Measure$ is a measure on this space.

A *Borel measure* is the measure $\Measure$ on a topological measure space $(X,\SigmaAlgebra{B},\Measure)$ where $(X,\Topology)$ is Hausdorff.

A *regular (Borel) measure* is a measure on a Borel measure space $(X,\SigmaAlgebra{B},\Measure)$ such that the following hold:
\begin{enumerate}
    \item *Finite Compact Measure*: For any compact subset $K\subseteq X$, then $\Measure(K)<\infty$.
    \item *Outer Regularity*: For any $B\in\SigmaAlgebra{B}$, then
    $$\Measure(B)=\inf\{\Measure(C)\mid B\subseteq C, C\text{ is open} \}. $$
    \item *Inner Regularity*: For any $U\in\Topology$, or, in other words, any open subset $U\subseteq X$, then
    $$\Measure(U)=\sup\{\Measure(K)\mid K\subseteq U, K\text{ compact} \}. $$
\end{enumerate}

A *left-Haar measure* [or *right-Haar measure*] on a topological group $(\Group,\Topology)$ is a non-zero regular Borel measure $\Measure$ on $\Group$ such that $\Measure(\GroupOperation{\GroupElement}{B})=\Measure(B)$ [or $\Measure(\GroupOperation{B}{\GroupElement})=\Measure(B)$] for all $\GroupElement\in\Group$ and $B\in\sigma(\Topology)$.
:::